ticketshop/ticketshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login
from django.views.generic.base import RedirectView, TemplateView

from tickets.views import (
    index, confirmation, details,
    edit_registration, cancel_registration)
from reports.views import report


admin.autodiscover()

urlpatterns = [
    # Tickets
    url(r'^$', index, name='index'),
    url(r'^register/(\d+)$', details, name='details'),
    url(r'^r/([\w-]+)/$', confirmation, name='confirm'),
    url(r'^r/([\w-]+)/edit$', edit_registration, name='edit'),
    url(r'^r/([\w-]+)/cancel$', cancel_registration, name='cancel'),
    # Reports
    url(r'^admin/report/$', RedirectView.as_view(url='/report/')),
    url(r'^report/$', report),
    # Built-in
    url(r'404/', TemplateView.as_view(template_name='404.html')),
    url(r'^accounts/login/$', login, {'template_name': 'admin/login.html'}),
    url(r'^admin/', include(admin.site.urls)),
]

ticketshop/tickets/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime
import uuid

from django.core.validators import RegexValidator
from django.db import models
from django.db.models import Count, Q, F
from django.dispatch import Signal

from .mails import (
    send_payment_confirmation_email,
    send_cancellation_email)
from .utils import randrefnumber


class TicketTypeManager(models.Manager):
    """
    Create a custom manager with an extra method
    that only returns available ticket types
    """
    def available(self):
        """
        Custom method that return a queryset with only
        available tickets
        """
        return super(TicketTypeManager, self).get_query_set() \
            .annotate(num_sold=Count('ticket')) \
            .filter(Q(quantity=None) | Q(num_sold__lt=F('quantity')))


class TicketType(models.Model):
    """
    A type of ticket is for instance "regular", "early bird", etc.

    """
    name = models.CharField(
        max_length=200,
        help_text="How do you call this kind of ticket? E.g. \"Early bird\"")
    description = models.TextField(
        blank=True,
        help_text="What does this ticket gives access to and who can by it.")
    price = models.IntegerField(help_text="Price in SEK.")
    sales_end = models.DateField(
        help_text="After this, it won't be possible to buy this ticket type.")
    quantity = models.IntegerField(
        null=True,
        blank=True,
        help_text="Maximum number of ticket of this type.")

    # Add our custom manager
    objects = TicketTypeManager()

    def __unicode__(self):
        return u"%s" % (self.name)

    def remaining(self):
        """ Return the number of tickets remaining of this type """
        return self.quantity

    def available(self, n=1):
        if self.quantity is None:
            return True
        else:
            return self.ticket_set.count() + n <= self.quantity

    class Meta:
        ordering = ['-price']


def default_ticket_type():
    Q = TicketType.objects.order_by('-price')
    if Q.count() > 0:
        return Q[0]
    else:
        return None


class Ticket(models.Model):
    ticket_type = models.ForeignKey(TicketType, default=default_ticket_type)
    name_on_badge = models.CharField(max_length=200)
    # Gender distribution, as required by the manifesto.
    # For a discussion on more inclusive gender question, see
    # http://itspronouncedmetrosexual.com/2012/06/how-can-i-make-the-gender-question-on-an-application-form-more-inclusive/
    gender = models.CharField(
        max_length=1,
        blank=True,
        verbose_name="I identify my gender as…",
        help_text="Why are we asking this? We ask you for your gender in \
                   order to evaluate our effort in reaching a fair and \
                   reasonable, within 60/40, gender distribution among \
                   participants.",
        choices=(('F', 'Woman'), ('M', 'Man'), ('T', 'Trans*'),
                 ('?', 'Prefer not to disclose'))
    )
    returning_visitor = models.NullBooleanField(
        blank=True,
        verbose_name="I have been to FSCONS before",
        choices=((True, 'Yes'), (False, 'No')),
    )
    purchase = models.ForeignKey("TicketPurchase", related_name="tickets")

    class Meta:
        permissions = (("view_reportk", "Can see the ticket report"),)

    def __unicode__(self):
        return u"{0.name_on_badge} ({0.ticket_type})".format(self)


class PreBooking(models.Model):
    """
    A pre-booking is a time-limited hold on a set of tickets.
    When a user start a new registration by selecting how many tickets they
    want to buy, we create a new pre-booking to hold those tickets for a given
    number of minutes.  When the registration is completed and a new
    TicketPurchase object is created in the database, the pre-booking should be
    deleted.  Alternatively, after the decided amount of time, the pre-booking
    is considered expired and the held-up tickets available again.

    Note that the natural key is the combination of session_id and ticket_type
    but since django doesn't support compound keys, there is also a surrogate
    key.
    """

    session = models.CharField(max_length=40)
    ticket_type = models.ForeignKey(TicketType)
    quantity = models.IntegerField()
    creation_date = models.DateTimeField(auto_now_add=True)
    expiration_date = models.DateTimeField()

    class Meta:
        unique_together = (('session', 'ticket_type'),)

    def __unicode__(self):
        return "{0.quantity} x {0.ticket_type}, {0.session}".format(self)


class TicketPurchase(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # Contact details
    contact_first_name = models.CharField(
            verbose_name="First name",
            max_length=200)
    contact_surname = models.CharField(
        verbose_name="Surname",
        max_length=200)
    contact_email = models.EmailField(
            verbose_name="E-mail")
    contact_subscribe = models.BooleanField(
            default=False,
            verbose_name="I would like to get emails about future conferences")
    additional_information = models.TextField(
        blank=True,
        help_text="Do not hesitate to let us know if you have specific \
                   requirements or comments about the registration.")
    paid = models.BooleanField(default=False, editable=False)
    # Administrativia
    creation_date = models.DateTimeField(editable=False, auto_now_add=True)
    ref = models.CharField(max_length=10, unique=True,
                           default=randrefnumber,
                           validators=[RegexValidator(regex=r"^\d{10}$")])

    cancelled = models.BooleanField(default=False, editable=False)
    cancelled_by = models.CharField(
        max_length=5, choices=(('USER', 'User'), ('ADMIN', 'Admin')),
        null=True, blank=True, editable=False)
    cancellation_date = models.DateTimeField(editable=False, null=True)

    def __unicode__(self):
        return u"%s %s (%d ticket(s))" % (
                self.contact_first_name,
                self.contact_surname,
                self.number_of_tickets())

    def price(self):
        p = 0
        for ticket in self.tickets.all():
            p += ticket.ticket_type.price
        return p

    def contact_full_name(self):
        return u"%s %s" % (self.contact_first_name, self.contact_surname)

    def get_contact_mailbox(self):
        """ Get the contact 'mailbox', in the form
          First Last <Address>
        suitable to use when sending emails.
        """
        return (u"{} <{}>"
                .format(self.contact_full_name(), self.contact_email))

    def number_of_tickets(self):
        return self.tickets.count()

    def mark_as_paid(self):
        """
        Mark an unpaid purchase as paid and send a purchase_paid signal
        """
        if not self.paid:
            self.paid = True
            self.save(update_fields=['paid'])
            purchase_paid.send(sender=self, purchase=self)

    def cancel(self, by):
        assert by in ['USER', 'ADMIN']
        self.cancelled = True
        self.cancellation_date = datetime.now()
        self.cancelled_by = by
        if by == "USER":
            send_cancellation_email(self)


# ~~~ Custom signals ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
purchase_paid = Signal(providing_args=["purchase"])


# ~~~ Signal handlers ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
def send_mail_on_paiement(sender, purchase, **kwargs):
    send_payment_confirmation_email(purchase)
purchase_paid.connect(send_mail_on_paiement)

ticketshop/tickets/views.py
from datetime import datetime, timedelta

from django.conf import settings
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404, render

from .forms import TicketSelectionForm, TicketPurchaseForm, TicketForm
from .mails import send_booking_confirmation_email
from .models import TicketPurchase, TicketType, Ticket, PreBooking
from .utils import randrefnumber


def index(request):
    """
    Index view: shows a form with a list of ticket that one can buy
    """
    ticket_types = TicketType.objects.all()
    form = TicketSelectionForm(ticket_types, request.POST or None)
    if request.session.session_key is None:
        request.session.create()

    if form.is_valid():
        quantities = form.cleaned_data
        PreBooking.objects.filter(session=request.session.session_key).delete()
        prebooking_expiration = (
            datetime.now() + timedelta(minutes=settings.PREBOOKING_TIMEOUT))
        for ticket_type in ticket_types:
            PreBooking.objects.create(
                session=request.session.session_key,
                ticket_type=ticket_type,
                quantity=quantities['quantity:{0.id}'.format(ticket_type)],
                expiration_date=prebooking_expiration)
        return redirect('details', randrefnumber())

    return render(request, "index.html", dict(form=form))


def details(request, ref):
    """
    Once the user has selected what tickets they wants to buy,
    this view will let them enter the details.
    """
    sid = request.session.session_key
    if sid is None or not PreBooking.objects.filter(session=sid).exists():
        messages.warning(request, "Your session has expired")
    pre_bookings = PreBooking.objects.filter(
        session=sid, expiration_date__gt=datetime.now())
    if not pre_bookings.exists():
        messages.warning(request, "Your registration has expired")
        return redirect('index')
    purchase_form = TicketPurchaseForm(request.POST or None)
    ticket_forms = []
    for pre_booking in pre_bookings:
        for _ in range(pre_booking.quantity):
            ticket_forms.append(
                TicketForm(
                    request.POST or None,
                    prefix="ticket%i" % len(ticket_forms),
                    instance=Ticket(ticket_type=pre_booking.ticket_type)))
    if purchase_form.is_valid() and all(f.is_valid() for f in ticket_forms):
        purchase = purchase_form.instance
        purchase.ref = ref
        purchase.save()
        for f in ticket_forms:
            f.instance.purchase = purchase
            f.instance.save()
        pre_bookings.delete()
        send_booking_confirmation_email(purchase)
        return redirect('confirm', purchase.id)
    return render(
        request,
        "details.html",
        dict(
            purchase_form=purchase_form,
            ticket_forms=ticket_forms,
            expiration_date=pre_bookings[0].expiration_date,
            PREBOOKING_TIMEOUT=settings.PREBOOKING_TIMEOUT,
            ))


def edit_registration(request, uuid):
    """
    A view that allows the attendee to edit their registration.
    """
    purchase = get_object_or_404(TicketPurchase, pk=uuid)
    purchase_form = TicketPurchaseForm(request.POST or None, instance=purchase)
    ticket_forms = []
    for i, ticket in enumerate(purchase.tickets.all()):
        ticket_forms.append(TicketForm(request.POST or None,
                                       prefix="ticket%i" % i,
                                       instance=ticket))
    if purchase_form.is_valid() and all(f.is_valid() for f in ticket_forms):
        purchase_form.instance.save()
        for form in ticket_forms:
            form.instance.save()
        return redirect('confirm', purchase.id)
    return render(request, "details.html",
                  dict(purchase_form=purchase_form, ticket_forms=ticket_forms))


def cancel_registration(request, uuid):
    """
    A view allowing the user to cancel their registration.
    When called with GET, it shows a confirmation dialog.
    The user confirms using POST.
    A paid registration cannot be cancelled this way.
    """
    purchase = get_object_or_404(TicketPurchase, pk=uuid)
    if purchase.paid:
        messages.warning(
            request,
            "This purchase has already been paid. "
            "If you still want to cancel it, please contact us at "
            "<a href='mailto:info@fscons.org'>info@fscons.org</a>")
        return redirect('confirm', purchase.id)
    if purchase.cancelled:
        messages.warning(request, "Purchase already cancelled")
        return redirect('confirm', purchase.id)
    if request.POST:
        action = request.POST.get('action', None)
        if action == 'confirm':
            purchase.cancel(by="USER")
            purchase.save()
            messages.success(request, "Registration successfully cancelled")
        return redirect('confirm', purchase.id)
    return render(request, "cancellation.html", dict(registration=purchase))


def confirmation(request, uuid):
    """ Show a summary of the purchase and the payment information """
    purchase = get_object_or_404(TicketPurchase, pk=uuid)
    return render(request, "confirmation.html", {'purchase': purchase})

ticketshop/tickets/templates/bootstrap-form-group.html
<div class="form-group {% if field.errors%}has-error{% endif %}">
  <label class="control-label col-sm-5" for="{{ field.id}}">
    {{ field.label }}
  </label>
  <div class="col-sm-5">
    {{ field }}
    {% if field.help_text %}
    <span class="help-block">{{ field.help_text }}</span>
    {% endif %}
    {% for error in field.errors %}
    <span class="text-danger">{{ error|escape }}</span>
    {% endfor %}
  </div>
</div>

ticketshop/tickets/templates/cancellation.html
{% extends "layout.html" %}

{% block "content" %}
  <h2>Confirmation required</h2>
  <p class="text-danger">You are going to cancel the following registration.
  Are you ABSOLUTELY sure?

  <p>Registration for {{ registration.contact_full_name }} including the
  following tickets:

  <ul>
    {% for ticket in registration.tickets.all %}
    <li>{{ ticket.name_on_badge }}
    {% endfor %}
  </ul>

  <form action="" method="POST">
    {% csrf_token %}
    <button id='btn-cancel' class="btn btn-default" name='action' value='cancel'>
      No, I want to keep my registration
    </button>
    <button id='btn-confirm' class="btn btn-danger" name='action' value='confirm'>
      I am sure, cancel my registration</button>

  </form>
{% endblock %}

ticketshop/tickets/templates/confirmation.html
{% extends "layout.html" %}

{% block "content" %}
<div class="row">
  <div class="col-md-8">
    {% if purchase.cancelled %}
    <div class="alert alert-warning" role="alert">
      <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
      <strong>Cancelled</strong>
      This registration has been cancelled.
    </div>
    {% else %}
    
    <p>Your ticket has been reserved. Please proceed with any of the payment
options below. We will reserve your ticket for up to one week awaiting
payment.</p>

    <h2>Payment</h2>
    <h3>Using bank transfer</h3>

    <p><strong>From Sweden:</strong> Transfer {{purchase.price}} SEK to Pulgiro
    <code>477884-1</code> or Bankgiro <code>311-5060</code>, add the reference
    number <code>{{purchase.ref}}</code> in the message of your transaction.

    <p><strong>From abroad:</strong> Transfer {{purchase.price}} SEK to IBAN
    <code>SE27 9500 0099 6026 0477 8841</code> (BIC: <code>NDEASESS</code>),
    add the reference number <code>{{purchase.ref}}</code> in the message of
    your transaction.

    <h3>Using bitcoin</h3>
    Transfer {{purchase.price}} SEK to <code>1CW9EUxrr3BULjcgG6Lc4ZUHahLSXUBSeU</code>, add the
    reference number <code>{{purchase.ref}}</code> in the message to your transaction.
    <h3>Using paypal</h3>
    Transfer {{purchase.price}} SEK to <code>paypal@fscons.org</code>, add the
    reference number <code>{{purchase.ref}}</code> in the message to your transaction.

    {% endif %}
  </div>


  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">
          Order summary
          {% if purchase.cancelled %}(<strong class="text-danger">CANCELLED</strong>){% endif %}
        </h2>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Name:
          <dd id="contact-name">{{ purchase.contact_first_name }} {{ purchase.contact_surname }}
          <dt>Email:
          <dd id="contact-email">{{purchase.contact_email}}
          <dt>I would like to get emails about future conferences...
          <dd id="contact-email">{{ purchase.contact_subscribe | yesno:"Yes,No" }}
        </dl>
      </div>
      <div class="list-group">
      {% for ticket in purchase.tickets.all %}
        <div class="list-group-item">
          <h4 class="list-group-item-heading">Ticket {{forloop.counter}} <small>({{ticket.ticket_type}})</small></h4>
          <dl class="list-group-item-text">
            <dt>Name on Badge
            <dd id="ticket{{forloop.counter}}-name_on_badge">
              {{ticket.name_on_badge}}
            <dt>I identify my gender as...
            <dd id="ticket{{forloop.counter}}-gender">
              {{ ticket.get_gender_display | default:"<i>unspecified</i>" }}
            <dt>I have been to FSCONS before...
            <dd id="ticket{{forloop.counter}}-returning_visitor">
              {{ticket.get_returning_visitor_display | default:"<i>unspecified</i>" }}
          </dl>
        </div>
      {% endfor %}
      </div>
      {% if not purchase.cancelled %}
      <div class="panel-body text-right">
        <a class="btn btn-default" href="{% url 'edit' purchase.id %}"
           role="button" id="btn-edit">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          Edit
        </a>

        <a class="btn btn-danger" href="{% url 'cancel' purchase.id %}"
           role="button" id="btn-cancel">
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          Cancel
        </a>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

ticketshop/tickets/templates/details.html
{% extends "layout.html" %}

{% block "content" %}
{% if expiration_date %}
<div class="alert alert-warning" role="alert">
  <div class="row">
    <div class="col-md-1" style="font-size:2em" id="countdown">
    </div>
    <div class="col-md-9">
      Please complete registration within {{PREBOOKING_TIMEOUT}}:00 minutes.<br/>
      After {{PREBOOKING_TIMEOUT}}:00 minutes, the reservation we're holding will be released to others.
    </div>
  </div>
</div>
{% endif %}

<form role="form" action="" method="POST" style="background:#F8F8F8;padding: 1em" class="form-horizontal">
  {% csrf_token %}
  <fieldset><legend>Contact information</legend>
    {% include "bootstrap-form-group.html" with field=purchase_form.contact_first_name %}
    {% include "bootstrap-form-group.html" with field=purchase_form.contact_surname %}
    {% include "bootstrap-form-group.html" with field=purchase_form.contact_email %}
    {% with field=purchase_form.contact_subscribe %}
    <div class="form-group {% if field.errors%}has-error{% endif %}">
      <div class="col-sm-offset-5 col-sm-5">
        <div class="checkbox">
          <label for="{{ field.id}}">
            {{ field }} {{ field.label }}
          </label>
          {% for error in field.errors %}
          <span class="text-danger">{{ error|escape }}</span>
          {% endfor %}
        </div>
      </div>
    </div>
    {% endwith %}
  </fieldset>
  {% for ticket_form in ticket_forms %}
    <fieldset>
      <legend>Ticket {{forloop.counter}} <small class="text-muted">({{ticket_form.instance.ticket_type}})</small></legend>
      {% include "bootstrap-form-group.html" with field=ticket_form.name_on_badge %}
      {% include "bootstrap-form-group.html" with field=ticket_form.email %}
      {% include "bootstrap-form-group.html" with field=ticket_form.gender %}
      {% include "bootstrap-form-group.html" with field=ticket_form.returning_visitor %}
    </fieldset>
  {% endfor %}
  <div class="control-group row">
    <button type="submit" class="btn btn-primary col-lg-6 col-md-offset-3"
            id="btn-checkout">
        Checkout
    </button>
  </div>
</form>

{% if expiration_date %}
<script type="text/javascript">
  $("#countdown")
    .countdown("{{expiration_date|date:"Y/m/d H:i:s"}}")
    .on('update.countdown', function(event) {
      $(this).text(event.strftime('%M:%S'));
    })
    .on('finish.countdown', function(event) {
      alert("You have exceeded the time limit and your reservation has been"
          +"released. You will now be redirected to the start page.");
      window.location.href = "{% url 'index' %}";
    });
</script>
{% endif %}
{% endblock %}

ticketshop/tickets/templates/index.html
{% extends "layout.html" %}

{% block "content" %}

    {% for error in form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
            {{error}}
    </div>
    {% endfor %}
<div class="row">
  <div class="col-md-6">

    <p>Join us during our two full days of talks and social events where you
    meet, greet, and share information in areas related to our three pillars:
    Society, Technology and Culture.

    <p>Celebrating our tenth anniversary, FSCONS 2016 will take place at
    <a href="https://www.marstrands.se/">Marstrands Havshotell</a>,
    beautifully situated on the west coast of Sweden.

    <p>As such, there will be a few differences to our usual conference.

    <ul>
      <li> There will be no tracks or themes, and no keynotes. Instead, we have
        invited 12 fantastic speakers. Some are among our favourites from
        previous conferences, some are people we have previously invited but
        that were unable to come before, and some are people doing new and
        exiting things.

      <li> The number of participants is limited to the number of rooms in the
        hotel, which is about 100. The participation fee will be somewhat
        higher than previous years. However, this price includes all meals and
        one night at the hotel, and corresponds to the actual cost per
        participant. As such, there will be no early bird tickets.

      <li> Depending on our luck in getting sponsors, we may be able to refund
        some of the costs for participants. We will put up an application form
        for this as the conference approaches and divide any surplus fairly
        among applicants.
    </ul>

    <p class="more"><strong>Free Society Conference and Nordic Summit</strong>
    FSCONS exists to provide a meeting place where subjects covering society,
    culture and technology can be discussed and brought to life in peer
    discussions, without being confined to each particular subject area. It should
    provide both the physical and virtual space where people, organisations and
    governments, with interest in the three subject areas can meet in a
    participatory and constructive dialogue. The unique combination of topics
    creates a platform where cross-pollination between the areas can occur, and
    where new co-operations and thoughts can emerge which allows the participants
    to find new inspiration even from areas outside of their own.

    <p>If you encounter any problems while registering, we would appreciate
    your feedback so that we can ensure that the problems are corrected. Please
    email info@fscons.org in this case, or if you wish to register in another
    way.
  </div>

  <div class=col-md-6>
    <form role="form" action="" method="POST" style="background:#F8F8F8;padding: 1em">
      {% csrf_token %}
      <fieldset><legend>FSCONS 2016 tickets</legend>
        <table class="table">
          <col width="40%">
          <col width="20%">
          <col width="20%">
          <col width="20%">
          <thead>
            <tr>
              <th>Ticket type</th>
              <th>Sales end</th>
              <th>Price</th>
              <th>Quantity</th>
            </tr>
          </thead>
          <tbody>
            {% for type_ in form.ticket_types %}<tr>
              <td>{{ type_.name }}
                <spann class="help-block">{{type_.description}}</span>
              <td>{{ type_.sales_end }}
              <td>{{ type_.price }} SEK
              <td>
                {% if type_.available %}
                  <select name="quantity:{{ type_.id }}">
                    <option>0</option>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                    <option>5</option>
                    <option>6</option>
                    <option>7</option>
                    <option>8</option>
                    <option>9</option>
                    <option>10</option>
                  </select>
                {% else %}
                  <strong>Sold out</strong>
                {% endif %}
            <tr>{% endfor %}
          </tbody>
        </table>
      </fieldset>
      <div class="control-group row">
        <button type="submit" class="btn btn-primary col-lg-6 col-md-offset-3"
                id="btn-register">
            Register
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

ticketshop/tickets/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>FSCONS 2016 Registration | FSCONS</title>

   <!-- Bootstrap compiled and minified CSS -->
   <link rel="stylesheet" href="{{ STATIC_URL }}/bootstrap-3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
   <!-- Optional theme -->
   <link rel="stylesheet" href="{{ STATIC_URL }}/bootstrap-3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- JQuery -->
  <script src="{{ STATIC_URL }}jquery-3.1.0.min.js"></script>
  <script src="{{ STATIC_URL }}jquery.countdown-2.2.0/jquery.countdown.min.js"></script>
</head>
<body>
<div id="wrap">
  <div class="wrapper container" id="main">
    <h1>FSCONS 2016 Registration</h1>
    {% for message in messages %}
    <div class="alert
      {% if 'info' in message.tags %}alert-info{% endif %}
      {% if 'success' in message.tags %}alert-success{% endif %}
      {% if 'warning' in message.tags %}alert-warning{% endif %}
      {% if 'error' in message.tags %}alert-danger{% endif %}
    ">
      {{ message | safe }}
    </div>
    {% endfor %}
    {% block "content" %}{% endblock %}
  </div>
  <footer class="container text-center" style="margin-top:3em">
    <hr />
    <div class="row">
      <ul class="nav nav-pills nav-justified">
        <li><a href="https://fscons.org/">
            <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
            FSCONS 2016</a></li>
        <li><a href="mailto:info@fscons.org">
            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
            Contact us</a></li>
        <li><a href="https://gitlab.com/fscons/ticketshop/issues">
            <span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span>
            Bugs / Feedback
        </a></li>
      </ul>
    </div>
  </footer>
</div>
    {% block extra_js %}{% endblock extra_js %}
</body>
</html>

ticketshop/tickets/templates/paypal_return.html
{% extends "layout.html" %}
{% comment %}
This is the page that will be displayed when the user comes back from paypal
after having completed the transaction.
{% endcomment %}

{% block "content" %}
<span class="byline">FSCONS 2012, November 09‒11</span>
<br/>
<br/>
<p>We are processing your payment. This can takes a few minutes. You will receive a confirmation email when it's done. Thank you!<br/><em>Vi ses i Göteborg!</em></div>
{% endblock %}